# Generated by Django 3.2 on 2021-06-04 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaluador',
            fields=[
                ('RNA', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Codigo RNA (Obligatorio)')),
                ('Identificacion', models.BigIntegerField(unique=True)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('Year', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('Email1', models.EmailField(max_length=254, verbose_name='Email (Obligatorio)')),
                ('Email2', models.EmailField(blank=True, max_length=254)),
                ('Telefono', models.CharField(blank=True, max_length=100)),
                ('Fax', models.CharField(blank=True, max_length=100)),
                ('Celular', models.CharField(max_length=100, verbose_name='Telefono Movil (Obligatorio)')),
                ('Direccion', models.CharField(blank=True, max_length=100)),
                ('Ciudad', models.CharField(blank=True, max_length=100)),
                ('ConReg', models.CharField(blank=True, max_length=100)),
                ('Afliado', models.BooleanField()),
                ('Fallecido', models.BooleanField()),
                ('Suspendido', models.BooleanField()),
                ('Comentarios', models.TextField(blank=True)),
                ('Codinter', models.CharField(blank=True, max_length=100, verbose_name='Codigo Internacional')),
                ('Pais', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Avaluadores',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('Categoria', models.CharField(blank=True, max_length=100)),
                ('Codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Solicitud', models.DateField()),
                ('Aprobacion', models.DateField()),
                ('Otorgamiento', models.DateField()),
                ('PrimerVencimiento', models.DateField()),
                ('Renovacion', models.DateField()),
                ('Vencimiento', models.DateField()),
                ('RNA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.avaluador')),
            ],
            options={
                'verbose_name_plural': 'Examenes',
            },
        ),
    ]
