# Generated by Django 3.2 on 2021-04-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaluador',
            fields=[
                ('RNA', models.BigIntegerField(primary_key=True, serialize=False)),
                ('CC', models.BigIntegerField(unique=True)),
                ('Nombre', models.CharField(max_length=100)),
                ('Year', models.SmallIntegerField()),
                ('Email1', models.EmailField(max_length=254)),
                ('Email2', models.EmailField(blank=True, max_length=254)),
                ('Telefono', models.CharField(blank=True, max_length=100)),
                ('Fax', models.CharField(blank=True, max_length=100)),
                ('Celular', models.CharField(blank=True, max_length=100)),
                ('Direccion', models.CharField(blank=True, max_length=100)),
                ('Ciudad', models.CharField(blank=True, max_length=100)),
                ('ConReg', models.CharField(blank=True, max_length=100)),
                ('Afliado', models.BooleanField()),
                ('Comentarios', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('Categoria', models.CharField(blank=True, max_length=100)),
                ('Codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Otorgamiento', models.DateField()),
                ('Renovacion', models.DateField()),
                ('Vencimiento', models.DateField()),
            ],
        ),
    ]
