# Generated by Django 3.2 on 2022-02-22 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaluador',
            fields=[
                ('RNA', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Codigo RNA (Obligatorio)')),
                ('Identificacion', models.CharField(max_length=100)),
                ('Nombre', models.CharField(max_length=200)),
                ('Apellidos', models.CharField(max_length=200)),
                ('Year', models.DateField(blank=True, verbose_name='Fecha de Nacimiento')),
                ('Telefono', models.CharField(blank=True, max_length=100)),
                ('Fax', models.CharField(blank=True, max_length=100)),
                ('Celular', models.CharField(max_length=100, verbose_name='Telefono Movil (Obligatorio)')),
                ('Direccion', models.CharField(blank=True, max_length=200)),
                ('Ciudad', models.CharField(blank=True, max_length=100)),
                ('ConReg', models.CharField(blank=True, max_length=100, verbose_name='Consejo Regional')),
                ('Comentarios', models.TextField(blank=True, max_length=1000)),
                ('Codinter', models.CharField(blank=True, max_length=100, verbose_name='Codigo Internacional')),
                ('Pais', models.CharField(blank=True, max_length=150)),
                ('Afiliado', models.CharField(blank=True, max_length=150)),
                ('TipoAfiliado', models.CharField(blank=True, max_length=150)),
                ('Titulo', models.CharField(default=' ', max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Avaluadores',
            },
        ),
        migrations.CreateModel(
            name='PersonaJuridica',
            fields=[
                ('NIT', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Codigo RNA (Obligatorio)')),
                ('ConReg', models.CharField(blank=True, max_length=100, verbose_name='Consejo Regional')),
                ('Telefono', models.CharField(blank=True, max_length=100)),
                ('Fax', models.CharField(blank=True, max_length=100)),
                ('Celular', models.CharField(blank=True, max_length=100, verbose_name='Telefono Movil (Obligatorio)')),
                ('Direccion', models.CharField(blank=True, max_length=200)),
                ('Nombre', models.CharField(max_length=200)),
                ('MatriculaRNA', models.CharField(blank=True, max_length=50)),
                ('RepresenanteApellidos', models.CharField(blank=True, max_length=100)),
                ('RepresenanteNombres', models.CharField(blank=True, max_length=100)),
                ('Comentarios', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=200)),
                ('PJ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bases.personajuridica')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bases.avaluador')),
            ],
        ),
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria', models.CharField(blank=True, choices=[('INTES', 'INTES'), ('URB', 'URB'), ('RUR', 'RUR'), ('ESP', 'ESP'), ('MYE', 'MYE')], max_length=30)),
                ('Codigo', models.CharField(max_length=30, verbose_name='Codigo Certificacion')),
                ('Otorgamiento', models.DateField(blank=True, null=True)),
                ('PrimerVencimiento', models.DateField(blank=True)),
                ('Renovacion', models.DateField(blank=True, null=True)),
                ('Vencimiento', models.DateField(blank=True, null=True)),
                ('RNA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.avaluador')),
            ],
            options={
                'verbose_name_plural': 'Certificaciones',
            },
        ),
        migrations.AddField(
            model_name='avaluador',
            name='PersonaJuridica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bases.personajuridica'),
        ),
    ]
