# Generated by Django 3.2 on 2021-06-02 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaluador',
            options={'verbose_name_plural': 'Avaluadores'},
        ),
        migrations.AlterModelOptions(
            name='examen',
            options={'verbose_name_plural': 'Examenes'},
        ),
        migrations.RenameField(
            model_name='avaluador',
            old_name='CC',
            new_name='Identificacion',
        ),
        migrations.AddField(
            model_name='avaluador',
            name='Apellidos',
            field=models.CharField(default=2313, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaluador',
            name='Codinter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='avaluador',
            name='Fallecido',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaluador',
            name='Pais',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='avaluador',
            name='Suspendido',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examen',
            name='Aprobacion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examen',
            name='PrimerVencimiento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examen',
            name='RNA',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='avaluador', to='bases.avaluador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examen',
            name='Solicitud',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
