# Generated by Django 3.2 on 2021-06-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='Categoria',
            field=models.CharField(blank=True, choices=[('INTES', 'INTES'), ('URB', 'URB'), ('RUR', 'RUR'), ('ESP', 'ESP'), ('MYE', 'MYE')], max_length=100),
        ),
    ]
