# Generated by Django 3.2 on 2021-06-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0002_auto_20210602_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='RNA',
        ),
    ]
