# Generated by Django 3.2 on 2021-06-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0002_alter_examen_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaluador',
            name='Afliado',
            field=models.BooleanField(verbose_name='Afiliado'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='Codigo',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Codigo Certificacion'),
        ),
    ]
