# Generated by Django 3.2 on 2021-06-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0003_remove_examen_rna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaluador',
            name='Celular',
            field=models.CharField(max_length=100, verbose_name='Telefono Movil (Obligatorio)'),
        ),
        migrations.AlterField(
            model_name='avaluador',
            name='Codinter',
            field=models.CharField(blank=True, max_length=100, verbose_name='Codigo Internacional'),
        ),
        migrations.AlterField(
            model_name='avaluador',
            name='Email1',
            field=models.EmailField(max_length=254, verbose_name='Email (Obligatorio)'),
        ),
        migrations.AlterField(
            model_name='avaluador',
            name='RNA',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Codigo RNA (Obligatorio)'),
        ),
        migrations.AlterField(
            model_name='avaluador',
            name='Year',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
    ]
