# Generated by Django 3.2 on 2021-07-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0003_auto_20210623_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaluador',
            name='Afliado',
            field=models.BooleanField(default=False, verbose_name='Afiliado'),
        ),
        migrations.AlterField(
            model_name='avaluador',
            name='Fallecido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='avaluador',
            name='Identificacion',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='avaluador',
            name='RNA',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Codigo RNA (Obligatorio)'),
        ),
        migrations.AlterField(
            model_name='avaluador',
            name='Suspendido',
            field=models.BooleanField(default=False),
        ),
    ]
