# Generated by Django 3.2 on 2021-06-04 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0004_auto_20210603_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='RNA',
            field=models.ForeignKey(default=123123, on_delete=django.db.models.deletion.CASCADE, to='bases.avaluador'),
            preserve_default=False,
        ),
    ]
