# Generated by Django 3.2 on 2022-02-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0005_auto_20220224_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='Email',
            new_name='EmailString',
        ),
    ]
