# Generated by Django 3.2 on 2022-03-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0006_rename_email_email_emailstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaluador',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
