# Generated by Django 4.0.3 on 2022-04-21 13:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0007_avaluador_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificacion',
            name='Vigencia',
        ),
        migrations.AddField(
            model_name='certificacion',
            name='VigenciaOtorgamiento',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Años de Vigencia Otorgamiento'),
        ),
        migrations.AddField(
            model_name='certificacion',
            name='VigenciaRenovacion',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Años de Vigencia Renovacion'),
        ),
        migrations.AlterField(
            model_name='certificacion',
            name='RNA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Certificacion', to='bases.avaluador'),
        ),
        migrations.AlterField(
            model_name='email',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Email', to='bases.avaluador'),
        ),
    ]
