# Generated by Django 3.2 on 2021-07-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0007_auto_20210728_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaluador',
            name='Identificacion',
            field=models.CharField(max_length=100),
        ),
    ]
