# Generated by Django 3.2 on 2021-07-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0008_alter_avaluador_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaluador',
            name='Apellidos',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='avaluador',
            name='Comentarios',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='avaluador',
            name='Direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='avaluador',
            name='Nombre',
            field=models.CharField(max_length=200),
        ),
    ]
