# Generated by Django 4.0.4 on 2022-05-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0008_remove_certificacion_vigencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaluador',
            name='Coordenadas',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AlterField(
            model_name='certificacion',
            name='Categoria',
            field=models.CharField(blank=True, choices=[('INTES URB', 'INTES URB'), ('INTES RUR', 'INTES RUR'), ('INTES ESP', 'INTES ESP'), ('INTES MYE', 'INTES MYE'), ('URB', 'URB'), ('RUR', 'RUR'), ('ESP', 'ESP'), ('MYE', 'MYE')], max_length=30),
        ),
    ]
