# Generated by Django 3.2 on 2021-08-11 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0009_auto_20210728_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaJuridica',
            fields=[
                ('NIT', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Codigo RNA (Obligatorio)')),
                ('ConReg', models.CharField(blank=True, max_length=100, verbose_name='Consejo Regional')),
                ('Telefono', models.CharField(blank=True, max_length=100)),
                ('Fax', models.CharField(blank=True, max_length=100)),
                ('Celular', models.CharField(max_length=100, verbose_name='Telefono Movil (Obligatorio)')),
                ('Direccion', models.CharField(blank=True, max_length=200)),
                ('Nombre', models.CharField(max_length=200)),
                ('RepresenanteApellidos', models.CharField(max_length=100)),
                ('RepresenanteNombres', models.CharField(max_length=100)),
                ('Comentarios', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='avaluador',
            name='ConReg',
            field=models.CharField(blank=True, max_length=100, verbose_name='Consejo Regional'),
        ),
        migrations.AddField(
            model_name='avaluador',
            name='PersonaJuridica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bases.personajuridica'),
        ),
    ]
