# Generated by Django 4.0.4 on 2022-05-05 17:13

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0010_alter_avaluador_coordenadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaluador',
            name='Coordenadas',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), null=True, srid=4326),
        ),
    ]
