# Generated by Django 3.2 on 2021-08-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0010_auto_20210811_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personajuridica',
            name='Celular',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telefono Movil (Obligatorio)'),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='RepresenanteApellidos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='RepresenanteNombres',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
