# Generated by Django 3.2 on 2022-02-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0012_auto_20220217_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaluador',
            name='Titulo',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
