# Generated by Django 3.2 on 2022-02-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0014_auto_20220217_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificacion',
            options={'verbose_name_plural': 'Certificaciones'},
        ),
        migrations.RemoveField(
            model_name='certificacion',
            name='Aprobacion',
        ),
        migrations.RemoveField(
            model_name='certificacion',
            name='Solicitud',
        ),
    ]
